### PR TITLE
Feature/#11 nullsafety

### LINKED ISSUE #11: Add nullsafety

### LINKED ISSUE #12: Version bump to the latest reactive ble package
Because of the outdated gradle system it is currently not possible to create new builds without this package upgrading to the latest version

### PR DESCRIPTION
**Pull request by vanlooverenkoen**
Fixed #11 
Fixed #12

### CODE REVIEW

**Comment by BeMacized** [comment]
Hi, thanks for putting in the work to add null safety! Code is looking great.

Building a fresh copy of the example app still seems to lead to a build error. It does look like this is more of an issue with flutter_reactive_ble. 

If this gets resolved I'd be happy to have this merged and published.

```
$ flutter run           
Running "flutter pub get" in example...                          1,342ms
Launching lib/main.dart on SM F916B in debug mode...
                                                            
FAILURE: Build completed with 2 failures.                               
                                                            
1: Task failed with an exception.                                       
-----------                                                             
* Where:                                                                
Build file '/Users/bemacized/.pub-cache/hosted/pub.dartlang.org/flutter_reactive_ble-3.0.0-nullsafety.0/android/build.gradle' line: 35
                                                            
* What went wrong:                                                      
A problem occurred evaluating project ':flutter_reactive_ble'.          
> Failed to apply plugin [id 'de.mannodermaus.android-junit5']          
> android-junit5 plugin requires Gradle 6.1.1 or later               
                                                            
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
                                                            
2: Task failed with an exception.                                       
-----------                                                             
* What went wrong:                                                      
A problem occurred configuring project ':flutter_reactive_ble'.         
> Failed to notify project evaluation listener.                         
> compileSdkVersion is not specified.                                
> Extension not initialized yet, couldn't access compileSdkVersion.  
                                                              
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
                                                              
* Get more help at https://help.gradle.org                              
                                                              
BUILD FAILED in 1s                                                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         4.3s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by vanlooverenkoen** [comment]
The gradle version is not yet updated to 6.1.1 or later I will do that later today or this week

**Comment by vanlooverenkoen** [comment]
Fixed the example

**Review by BeMacized — APPROVED** [review]
LGTM!

**Pull request merged**
